id: PCC4F0112
initial_creation_type: input
source_metadata:
  title: Dudjom Lingpa Series
  language: de
  description: 'We present the following texts by and about the great tertön Dudjom
    Lingpa (bdud ''joms gling pa, 1835–1904):'
  volume:
    0e677490a335423eae5dd2a877ddc1f4:
      title: A Sukhāvatī Prayer and Aspiration
      parent: Aspiration Prayers
    5a568ea5295644f79656dca6ff84f00a:
      title: An Aspiration
      parent: Aspiration Prayers
    4e27ee70c21c4adb987cdd9601b61350:
      title: An Aspiration Prayer
      parent: Aspiration Prayers
    fbdd6c2b11574e76a263253cc0bd8ef7:
      title: The Biography of the Great Orgyen that Naturally Liberates On Sight
      parent: Biography
    91fccbea37804196a97b9c940877eab7:
      title: Golden Drink (Serkyem) and Torma Offering
      parent: Offering
    1c4665e8ec8c46caa5ab43d6e51a1062:
      title: The Verse for Offering Water from the Pure Vision, An Ocean of Accomplishments
      parent: Offering
    7d43ea6e569947d782f09f1501986494:
      title: A Prayer
      parent: Prayers
    9b5012b4484a4ba1ba12ce78cf594360:
      title: A Prayer to Dudjom Lingpa
      parent: Prayers
    78e5a2fc801f48b396534b60264311d9:
      title: A Prayer to Padmasambhava
      parent: Prayers
    c1960146be7843f59dd0bb561938ccf5:
      title: A Prayer to Parṇaśavarī
      parent: Prayers
    daa59d6b56c14b8db995cf03f7f3395a:
      title: The Outer, Inner and Secret Refuge Prayer
      parent: Refuge
    28fd885bdb414171a99a718a210a0ff0:
      title: 'Making Great Bliss the Path: Visualisation and Mantra Recitation of
        Medicine Buddha'
      parent: Sādhanas
    809818ba0a6a47c381e0a6da5aa808ed:
      title: Visualization and Mantra Recitation of the Great Compassionate One
      parent: Sādhanas
created_at: '2022-02-28T23:06:52.943379'
last_modified_at: '2022-02-28T23:06:52.943381'
